TECH-861: fixes to gherkin and js tests
GovStackWorkingGroup/bb-messaging pull request #16
Opened 2023-09-19 14:37 UTC by lruzicki

## Description
- Messaging
  - `/callback/email`
    - Updated `callback_email.feature`
      - Added content type as "application/json"
      - Provided example of `requestUID`
  - `/send/email/batch`
    - Updated `send_email_batch.feature`
      - Added content type as "application/json"
  - `/send/email/single`
    - Updated `send_email_single.feature`
      - Added content type as "application/json"
  - `/status/email`
    - Updated `status_email.feature`
      - Added content type as "application/json"
      - Added tables with test data for negative tests (lines 94 and 119)
- Script Updates
  - Fixed typos in local test-running script
  - Added `--build` flag to Docker Compose command

## How Has This Been Tested?
Tests pass on local env

2023-09-20 11:07 UTC, dborowiecki requested changes

2023-09-20 11:07 UTC, dborowiecki commented on examples/mock/entrypoint.sh
is this file necessary? can we remove it?

2023-09-20 11:07 UTC, dborowiecki commented on test/openAPI/features/callback_email.feature
> +        When "POST" request with given "abcdef12345" as api_key and valid requestUID, for example "btpn-aiqu-urw8-94zm-h0av-vjhl", in the headers is sent
I don't think we should use "for example" in tests. Better option would be something more concise like: 
```gherkin
Given a single email with api_key "abcdef12345" and a valid payload is sent, returning a requestUID "btpn-aiqu-urw8-94zm-h0av-vjhl"
When a "POST" request with api_key "abcdef12345" and requestUID "btpn-aiqu-urw8-94zm-h0av-vjhl" in the headers is sent
```


This comment refeer also to other scenarios new steps with same syntax.

2023-09-26 08:13 UTC, lruzicki commented on examples/mock/entrypoint.sh
yes we can delete it

2023-09-29 10:37 UTC, dborowiecki approved these changes

2023-09-29 10:37 UTC, merged